name = "FantastiCreate"
author = "akai_hana"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "664042ed0e59e2ad0bc52435a58feca71a809f7e9392104a16e3ded18f837d44"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
