name = "FantastiCreate Dev Release 4"
author = "akai_hana"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8efd0cec81db752cd82b04650dbc8fcacb286456e1927fbbf05930aeda217cf"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
